version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: product_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:7.4-alpine
    container_name: product_redis
    # command: redis-server --save 20 1 --loglevel warning
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_api
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      FLASK_APP: app.app:create_app
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - app_network
    ports:
    - "5000:5000"

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: flask_worker
  #   command: python worker.py
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  #     REDIS_URL: redis://redis:6379/0
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
